import {
  schemaRenderBlock,
  schemaRenderBlockJsx,
  schemaRenderCell,
  schemaRenderCellJsx,
  schemaRenderDetailsActionBulk,
  schemaRenderDetailsActionBulkJsx,
  schemaRenderDetailsActionRow,
  schemaRenderDetailsActionRowJsx,
  schemaRenderField,
  schemaRenderFieldJsx,
  schemaRenderFormActionRow,
  schemaRenderFormActionRowJsx,
  schemaRenderTableActionBulk,
  schemaRenderTableActionBulkJsx,
  schemaRenderTableActionRow,
  schemaRenderTableActionRowJsx,
} from './component.ts';
import {
  schemaRenderDisableNotifyChanged,
  schemaRenderFieldSource,
  schemaRenderLayout,
  schemaRenderOrder,
  schemaRenderReadonly,
  schemaRenderVisible,
} from './rest.ts';

export const ZovaRender = {
  // render
  layout: schemaRenderLayout,
  visible: schemaRenderVisible,
  readonly: schemaRenderReadonly,
  order: schemaRenderOrder,
  disableNotifyChanged: schemaRenderDisableNotifyChanged,
  fieldSource: schemaRenderFieldSource,
  // component
  field: schemaRenderField,
  fieldJsx: schemaRenderFieldJsx,
  cell: schemaRenderCell,
  cellJsx: schemaRenderCellJsx,
  tableActionRow: schemaRenderTableActionRow,
  tableActionRowJsx: schemaRenderTableActionRowJsx,
  detailsActionRow: schemaRenderDetailsActionRow,
  detailsActionRowJsx: schemaRenderDetailsActionRowJsx,
  formActionRow: schemaRenderFormActionRow,
  formActionRowJsx: schemaRenderFormActionRowJsx,
  tableActionBulk: schemaRenderTableActionBulk,
  tableActionBulkJsx: schemaRenderTableActionBulkJsx,
  detailsActionBulk: schemaRenderDetailsActionBulk,
  detailsActionBulkJsx: schemaRenderDetailsActionBulkJsx,
  block: schemaRenderBlock,
  blockJsx: schemaRenderBlockJsx,
};
