packages:
  - 'packages-cli/*'
  - 'packages-utils/*'
  - 'packages-zova/*'
  - 'src/module/*'
  - 'src/module-vendor/*'
  - 'src/suite/*'
  - 'src/suite/*/modules/*'
  - 'src/suite-vendor/*'
  - 'src/suite-vendor/*/modules/*'

# shamefullyHoist: true
strictPeerDependencies: false
# to get the latest compatible packages when creating the project https://github.com/pnpm/pnpm/issues/6463
resolutionMode: 'highest'
hoist: true
hoistWorkspacePackages: true
linkWorkspacePackages: 'deep'
preferWorkspacePackages: true
autoInstallPeers: true
publicHoistPattern:
  - '*terser*'
  - '*babel*'
  - '*@babel*'
  - '*eslint*'
  - '*types*'
  - 'lerna'
  - 'cabloy'
  - '@cabloy'
  - '*cabloy*'
  - '*@cabloy*'
  - '*zova*'
  - '*vue*'
  - '*@vue*'
  - '*vite*'
  - '*@vitejs*'
  - '*zod*'
  - '*@tanstack*'
  - 'zod'

overrides:
  '@quasar/app-vite': 'npm:@cabloy/quasar-app-vite@^2.5.10'
  '@vue/babel-plugin-jsx': 'npm:@cabloy/vue-babel-plugin-jsx@^2.0.1'
  '@vue/compiler-dom': '3.5.13'
  '@vue/compiler-sfc': 'npm:@cabloy/vue-compiler-sfc@^3.5.14'
  '@vue/runtime-core': 'npm:@cabloy/vue-runtime-core@^3.5.57'
  '@vue/runtime-dom': 'npm:@cabloy/vue-runtime-dom@^3.5.13'
  '@vue/reactivity': 'npm:@cabloy/vue-reactivity@^3.5.16'
  '@vue/server-renderer': 'npm:@cabloy/vue-server-renderer@^3.5.18'
  '@vue/shared': '3.5.13'
  vue-router: 'npm:@cabloy/vue-router@^4.4.16'
  zod: 'npm:@cabloy/zod@4.3.6'

allowBuilds:
  '@parcel/watcher': true
  '@zhennann/ejs': true
  esbuild: true
  vue-demi: true
