packages:
  - 'packages-cli/*'
  - 'packages-docs'
  - 'packages-utils/*'
  - 'packages-vona/*'
  - 'src/module/*'
  - 'src/module-vendor/*'
  - 'src/suite/*'
  - 'src/suite/*/modules/*'
  - 'src/suite-vendor/*'
  - 'src/suite-vendor/*/modules/*'

hoist: true
hoistWorkspacePackages: true
linkWorkspacePackages: deep
preferWorkspacePackages: true
autoInstallPeers: true
publicHoistPattern:
  - '*babel*'
  - '*@babel*'
  - '*eslint*'
  - '*@eslint*'
  - '*types*'
  - lerna
  - vona
  - '*vona*'
  - cabloy
  - '@cabloy'
  - '*cabloy*'
  - '*@cabloy*'
  - '*why-is-node-running*'
  - '*ts-node*'
  - zod
onlyBuiltDependencies:
  - better-sqlite3
  - '@swc/core'
  - '@zhennann/ejs'
  - esbuild
  - msgpackr-extract
  - nx

overrides:
  '@types/mime': '3.0.4'
  '@types/react': 'npm:@cabloy/types-react@^19.2.16'
