packages:
  - 'packages-cli/*'
  - 'packages-utils/*'
  - 'packages-vona/*'
  - 'src/module/*'
  - 'src/module-vendor/*'
  - 'src/suite/*'
  - 'src/suite/*/modules/*'
  - 'src/suite-vendor/*'
  - 'src/suite-vendor/*/modules/*'

hoist: true
hoistWorkspacePackages: true
linkWorkspacePackages: deep
preferWorkspacePackages: true
autoInstallPeers: true
publicHoistPattern:
  - '*babel*'
  - '*@babel*'
  - '*eslint*'
  - '*@eslint*'
  - '*types*'
  - lerna
  - vona
  - '*vona*'
  - cabloy
  - '@cabloy'
  - '*cabloy*'
  - '*@cabloy*'
  - '*why-is-node-running*'
  - '*ts-node*'
  - zod

overrides:
  '@types/mime': '3.0.4'
  '@types/react': 'npm:@cabloy/types-react@^19.2.16'
  '@vue/compiler-dom': '3.5.36'
  '@vue/compiler-sfc': '3.5.36'
  '@vue/compiler-ssr': '3.5.36'
  '@vue/runtime-dom': '3.5.36'
  '@vue/server-renderer': '3.5.36'
  '@vue/shared': '3.5.36'
  zod: 'npm:@cabloy/zod@4.3.8'

allowBuilds:
  '@swc/core': true
  '@zhennann/ejs': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  vue-demi: true

patchedDependencies:
  zova-core@5.1.61: patches/zova-core@5.1.61.patch
