name: actions-test-pg
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      pg:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v5
        with:
          version: 10.19.0
      - run: cp package.original.json package.json
      - run: npm run init
      - run: DATABASE_DEFAULT_CLIENT=pg npm run test
      - run: DATABASE_DEFAULT_CLIENT=pg npm run build -- --flavor=ci
      - run: DATABASE_DEFAULT_CLIENT=pg npm run play -- --mode=prod --flavor=ci
