export const rules = {
  'e18e/prefer-spread-syntax': 'off',
  'e18e/prefer-object-has-own': 'off',
  'e18e/prefer-static-regex': 'off',
  'e18e/prefer-array-at': 'off',
  'e18e/prefer-regex-test': 'off',
  'regexp/no-unused-capturing-group': 'off',
  'test/no-only-tests': 'off',
  'test/no-import-node-test': 'off',
  'jsdoc/check-alignment': 'off',
  'no-extend-native': ['error', { exceptions: ['Set'] }],
  'no-new-func': 'off',
  'regexp/no-super-linear-backtracking': 'off',
  'no-template-curly-in-string': 'off',
  'n/prefer-global/process': 'off',
  'unicorn/error-message': 'off',
  'antfu/if-newline': 'off',
  'antfu/no-top-level-await': 'off',
  'antfu/top-level-function': 'off',
  'import/no-duplicates': 'off',
  'eslint-comments/no-unlimited-disable': 'off',
  'prefer-promise-reject-errors': 'off',
  'no-console': 'warn',
  'no-debugger': 'warn',
  'prefer-const': [
    'error',
    {
      destructuring: 'all',
      ignoreReadBeforeAssign: true,
    },
  ],
  'no-undef': [
    'error',
    {
      typeof: false,
    },
  ],
  'array-bracket-spacing': ['error', 'never'],
  'no-empty': [
    'error',
    {
      allowEmptyCatch: true,
    },
  ],
  'no-empty-function': [
    'error',
    {
      allow: [
        'functions',
        'arrowFunctions',
        'generatorFunctions',
        'methods',
        'generatorMethods',
        'getters',
        'setters',
        'constructors',
        'asyncFunctions',
        'asyncMethods',
      ],
    },
  ],
  'no-constant-condition': [
    'error',
    {
      checkLoops: false,
    },
  ],
  'one-var-declaration-per-line': [0],
  'space-before-function-paren': [0],
  'generator-star-spacing': [0],
  'newline-per-chained-call': [0],
  'prefer-rest-params': 'off',
  // 'no-setter-return': 'off', // no effect for typescript check
  '@typescript-eslint/method-signature-style': 'off',
  '@typescript-eslint/no-redeclare': 'off',
  '@typescript-eslint/consistent-type-imports': [
    'error',
    { fixStyle: 'separate-type-imports', prefer: 'type-imports' },
  ],
  '@typescript-eslint/explicit-function-return-type': 'off',
  '@typescript-eslint/no-namespace': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
  '@typescript-eslint/no-var-requires': 'off',
  'unused-imports/no-unused-vars': [
    'error',
    {
      args: 'all',
      argsIgnorePattern: '^_',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
      destructuredArrayIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      ignoreRestSiblings: true,
    },
  ],
  '@typescript-eslint/no-unused-vars': [
    'error',
    {
      args: 'all',
      argsIgnorePattern: '^_',
      caughtErrors: 'all',
      caughtErrorsIgnorePattern: '^_',
      destructuredArrayIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      ignoreRestSiblings: true,
    },
  ],
  '@typescript-eslint/no-this-alias': 'off',
  '@typescript-eslint/no-unsafe-declaration-merging': 'off',
  '@typescript-eslint/ban-ts-comment': [
    'error',
    {
      'ts-expect-error': 'allow-with-description',
      'ts-ignore': 'allow-with-description',
    },
  ],
  '@typescript-eslint/no-empty-object-type': 'off',
  '@typescript-eslint/no-unsafe-function-type': 'off',
  '@typescript-eslint/no-use-before-define': ['error', { functions: false }],
  '@stylistic/max-len': [
    'error',
    {
      code: 150,
      tabWidth: 2,
      ignoreComments: true,
      ignoreTrailingComments: true,
      ignoreUrls: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignoreRegExpLiterals: true,
    },
  ],
  '@stylistic/arrow-parens': ['error', 'as-needed'],
  '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: true }],
  '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
  '@stylistic/operator-linebreak': [
    'error',
    'after',
    { overrides: { '?': 'before', ':': 'before' } },
  ],
  '@stylistic/keyword-spacing': [
    'error',
    {
      overrides: {
        this: { before: true },
      },
    },
  ],
  '@stylistic/indent': [
    'error',
    2,
    {
      SwitchCase: 1,
      VariableDeclarator: 'first',
      outerIIFEBody: 1,
      MemberExpression: 1,
      FunctionDeclaration: { body: 1, parameters: 1 },
      FunctionExpression: { body: 1, parameters: 1 },
      StaticBlock: { body: 1 },
      CallExpression: { arguments: 1 },
      ArrayExpression: 1,
      ObjectExpression: 1,
      ImportDeclaration: 1,
      flatTernaryExpressions: true,
      offsetTernaryExpressions: true,
    },
  ],
  '@stylistic/jsx-closing-tag-location': 'off',
};
