module.exports = {
  auth: 'dingtalk-square,github,password,sms,wechat-outline,wxwork-outline',
  business: 'coupon,course,distribution,hotsprings,kitchen-set,money-bag,party,provider,purchase,store',
  default: 'add,alert,archive,arrow-back,arrow-cycle,arrow-down-left,arrow-down-right,arrow-down,arrow-drop-down,arrow-drop-up,arrow-forward,arrow-left,arrow-repeat,arrow-right-left,arrow-right,arrow-shuffle,arrow-up-down,arrow-up-left,arrow-up-right,arrow-up,article,attachment-line,book,cabloy,checkbox-checked,checkbox-intermediate,checkbox-off,checkbox,chevron-left,chevron-right,close,comment-dots,construction,copyright,cross-circle,dashboard,database,delete-forever,delete,developer-board,done,dot,draft,drive-file-move,edit,expand-more,export,fast-forward,flow-chart,folder-open,folder,fullscreen-exit,fullscreen,grading,group-work,group,groups,heart,home,identification,import,info-circle,information-filled,information,label,language,layers,layout-columns,location-on,lock-open,lock,mail,mark-as-unread,mark-email-read,menu,message,module,more-horiz,notebook,open-in-new,open-with,people,person,play-arrow,popup,preview,radio-button-checked,radio-button-unchecked,redo,remove,reply,round-person-add,save-and-return,save-and-submit,save-as-draft,save,search,send,settings,share,sort,star,stats-chart,stop,text-fields,undo,view-list,visibility,zoom-in,zoom-out',
  editor: 'add-box-outline,add-box,bookmark-outline,bookmark,code-block,code,format-align-center,format-align-left,format-align-right,format-bold,format-italic,format-list-bulleted,format-list-numbered,format-quote,format-strikethrough,format-underlined,grid-on,horizontal-rule,image-outline,image,insert-link-outline,paragraph-break,paragraph,redo,source-outline,subscript,superscript,task-alt,title,undo',
  flow: 'activity-none,activity-service,activity-user-task,end-event-atom,end-event-none,gateway-exclusive,gateway-inclusive,gateway-parallel,start-event-atom,start-event-none,start-event-timer',
  login: 'call-outline,chevron-left,done,lock-outline,person-outline',
  outline: 'add-circle-outline,alert-outline,apps-outline,archive-lock-outline,archive-outline,article-outline,backspace-outline,build-circle-outline,calendar-today-outline,check-circle-outline,checkbox-checked-outline,checkbox-off-outline,checkbox-outline,copy-outline,data-list-outline,database-lock-outline,delete-forever-outline,delete-outline,dict-outline,draft-outline,folder-transfer-outline,group-outline,heart-outline,insert-emoticon-outline,key-reset-outline,label-outline,layout-outline,login-outline,logout-outline,mail-outline,note-outline,software-resource-cluster-outline,software-resource-outline,star-outline,theme-outline,timer-outline,visibility-off-outline,visibility-outline,work-history-outline',
  role: 'level,organization,position,relation,role,shield-key,template',
  social: 'facebook,framework7,twitter',
  tools: 'pomotodo,spreadsheet',
};
